# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogenerate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
